### ISSUE TITLE
Analysing Previous Algorithms

### ISSUE THREAD

**Issue by koushik30027** [KSSC-ORG/SetCover#2]

**Comment by 2010030045-Chaitanya** [comment]
Let C represent the set of elements covered so far
Let cost effectiveness, or α , be the average cost per newly covered node
Algorithm
1. C <-- 0
2. While C ≠ U do
Find the set whose cost effectiveness is smallest, say S
          
Let α=c(S)/ |S-C|

For each e∈S-C, set price(e) = α
C <-- C ∪ S
3. Output picked sets
