### ISSUE TITLE
Algorithm

### ISSUE THREAD

**Issue by koushik30027** [KSSC-ORG/SetCover#3]

**Comment by SOUMITH30097** [comment]
The technique we are going to use in this application is greedy algorithm. It will add one set at a time to the set cover until every element in X is covered by at least one set
It will give best polynomial time to cover the more number of buildings with lesser number of food courts.
In this application it is more optimal when compared to previous algorithms.

**Comment by 2010030167** [comment]
![image](https://user-images.githubusercontent.com/95115248/158104411-2c5faa08-b200-4958-b8dc-85634f7b96ac.png)
